<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * Model events are left on. The organization slug is generated by a
     * creating hook and the default legal families by a created one, so an
     * organization made with events muted comes out with neither.
     */
    public function run(): void
    {
        $this->call(DemoSeeder::class);
    }
}
